-- 1. Create cat_photos table
create table if not exists public.cat_photos (
  id bigint generated by default as identity primary key,
  cat_id bigint references public.cats(id) on delete cascade not null,
  url text not null,
  user_id uuid references auth.users(id),
  created_at timestamptz default now()
);

-- 2. Create cat_sightings table
create table if not exists public.cat_sightings (
  id bigint generated by default as identity primary key,
  cat_id bigint references public.cats(id) on delete cascade not null,
  user_id uuid references auth.users(id),
  created_at timestamptz default now()
);

-- 3. Enable RLS
alter table public.cat_photos enable row level security;
alter table public.cat_sightings enable row level security;

-- 4. Create Policies
-- Photos
create policy "Public read access for cat_photos"
  on public.cat_photos for select
  using (true);

create policy "Authenticated insert for cat_photos"
  on public.cat_photos for insert
  with check (auth.role() = 'authenticated');

create policy "Authenticated delete for cat_photos"
  on public.cat_photos for delete
  using (auth.role() = 'authenticated');

-- Sightings
create policy "Public read access for cat_sightings"
  on public.cat_sightings for select
  using (true);

create policy "Authenticated insert for cat_sightings"
  on public.cat_sightings for insert
  with check (auth.role() = 'authenticated');

-- 5. Migrate existing images from 'cats' table to 'cat_photos'
-- Only insert if the image URL is not already in cat_photos for that cat
insert into public.cat_photos (cat_id, url)
select id, image
from public.cats
where image is not null
and not exists (
    select 1 from public.cat_photos where cat_id = cats.id and url = cats.image
);

-- 6. Grant usage/select on sequences (fixes permission errors)
grant  usage, select on sequence cat_photos_id_seq to authenticated, anon;
grant  usage, select on sequence cat_sightings_id_seq to authenticated, anon;
grant  all on public.cat_photos to authenticated, anon;
grant  all on public.cat_sightings to authenticated, anon;
