-- Enable PostGIS if we wanted strictly correct geo, but for now simple float is fine.
-- Enable extensions
create extension if not exists "uuid-ossp";

-- 1. Cats Table
create table public.cats (
  id bigint generated by default as identity primary key,
  name text not null,
  breed text,
  status text check (status in ('Healthy', 'Needs Help', 'Adopted')),
  description text,
  image text,
  latitude float8 not null,
  longitude float8 not null,
  last_fed timestamptz,
  last_sighted timestamptz default now(),
  tnr_status boolean default false,
  rescue_flags text[] default '{}',
  color_profile text[],
  location_description text,
  created_at timestamptz default now()
);

-- 2. Cat Feedings Table
create table public.cat_feedings (
  id bigint generated by default as identity primary key,
  cat_id bigint references public.cats(id) on delete cascade not null,
  food_type text,
  amount text,
  shared_with_others boolean default false,
  created_at timestamptz default now()
);

-- 3. Cat Translations Table
create table public.cat_translations (
  id bigint generated by default as identity primary key,
  cat_id bigint references public.cats(id) on delete cascade not null,
  translation text not null,
  sentiment text,
  created_at timestamptz default now()
);

-- Enable Row Level Security (RLS) - Optional but recommended
alter table public.cats enable row level security;
alter table public.cat_feedings enable row level security;
alter table public.cat_translations enable row level security;

-- Create policies (Open for all for this demo app)
-- Create policies (Restricted to authenticated users)
create policy "Enable read access for authenticated users" on public.cats for select using (auth.role() = 'authenticated');
create policy "Enable insert access for authenticated users" on public.cats for insert with check (auth.role() = 'authenticated');
create policy "Enable update access for authenticated users" on public.cats for update using (auth.role() = 'authenticated');
create policy "Enable delete access for authenticated users" on public.cats for delete using (auth.role() = 'authenticated');

create policy "Enable read access for authenticated users" on public.cat_feedings for select using (auth.role() = 'authenticated');
create policy "Enable insert access for authenticated users" on public.cat_feedings for insert with check (auth.role() = 'authenticated');

create policy "Enable read access for authenticated users" on public.cat_translations for select using (auth.role() = 'authenticated');
create policy "Enable insert access for authenticated users" on public.cat_translations for insert with check (auth.role() = 'authenticated');

-- 4. Community Posts Table
create table public.community_posts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  user_name text not null default 'Anonymous',
  avatar_url text,
  content text not null,
  image_url text,
  category text not null check (category in ('Sighting', 'Question', 'Medical Alert', 'Success Story', 'Urgent', 'TNR')),
  cat_tags text[] default '{}',
  likes_count int default 0,
  comments_count int default 0,
  created_at timestamptz default now()
);

-- 5. Community Comments Table
create table public.community_comments (
  id bigint generated by default as identity primary key,
  post_id bigint references public.community_posts(id) on delete cascade not null,
  user_id uuid references auth.users(id),
  user_name text not null default 'Anonymous',
  content text not null,
  created_at timestamptz default now()
);

-- 6. Community Likes Table
create table public.community_likes (
  id bigint generated by default as identity primary key,
  post_id bigint references public.community_posts(id) on delete cascade not null,
  user_id uuid references auth.users(id),
  created_at timestamptz default now(),
  unique(post_id, user_id)
);

alter table public.community_posts enable row level security;
alter table public.community_comments enable row level security;
alter table public.community_likes enable row level security;

create policy "Enable read access for all users" on public.community_posts for select using (true);
create policy "Enable insert access for authenticated users" on public.community_posts for insert with check (auth.role() = 'authenticated');
create policy "Enable update own posts" on public.community_posts for update using (auth.uid() = user_id);
create policy "Enable delete own posts" on public.community_posts for delete using (auth.uid() = user_id);

create policy "Enable read access for all users" on public.community_comments for select using (true);
create policy "Enable insert access for authenticated users" on public.community_comments for insert with check (auth.role() = 'authenticated');

create policy "Enable read access for all users" on public.community_likes for select using (true);
create policy "Enable insert access for authenticated users" on public.community_likes for insert with check (auth.role() = 'authenticated');
create policy "Enable delete own likes" on public.community_likes for delete using (auth.uid() = user_id);
