-- Enable PostGIS if we wanted strictly correct geo, but for now simple float is fine.
-- Enable extensions
create extension if not exists "uuid-ossp";

-- 1. Cats Table
create table public.cats (
  id bigint generated by default as identity primary key,
  name text not null,
  breed text,
  status text check (status in ('Healthy', 'Needs Help', 'Adopted')),
  description text,
  image text,
  latitude float8 not null,
  longitude float8 not null,
  last_fed timestamptz,
  last_sighted timestamptz default now(),
  tnr_status boolean default false,
  rescue_flags text[] default '{}',
  color_profile text[],
  location_description text,
  created_at timestamptz default now()
);

-- 2. Cat Feedings Table
create table public.cat_feedings (
  id bigint generated by default as identity primary key,
  cat_id bigint references public.cats(id) on delete cascade not null,
  food_type text,
  amount text,
  shared_with_others boolean default false,
  created_at timestamptz default now()
);

-- 3. Cat Translations Table
create table public.cat_translations (
  id bigint generated by default as identity primary key,
  cat_id bigint references public.cats(id) on delete cascade not null,
  translation text not null,
  sentiment text,
  created_at timestamptz default now()
);

-- Enable Row Level Security (RLS) - Optional but recommended
alter table public.cats enable row level security;
alter table public.cat_feedings enable row level security;
alter table public.cat_translations enable row level security;

-- Create policies (Open for all for this demo app)
-- Create policies (Restricted to authenticated users)
create policy "Enable read access for authenticated users" on public.cats for select using (auth.role() = 'authenticated');
create policy "Enable insert access for authenticated users" on public.cats for insert with check (auth.role() = 'authenticated');
create policy "Enable update access for authenticated users" on public.cats for update using (auth.role() = 'authenticated');
create policy "Enable delete access for authenticated users" on public.cats for delete using (auth.role() = 'authenticated');

create policy "Enable read access for authenticated users" on public.cat_feedings for select using (auth.role() = 'authenticated');
create policy "Enable insert access for authenticated users" on public.cat_feedings for insert with check (auth.role() = 'authenticated');

create policy "Enable read access for authenticated users" on public.cat_translations for select using (auth.role() = 'authenticated');
create policy "Enable insert access for authenticated users" on public.cat_translations for insert with check (auth.role() = 'authenticated');
